-- 1. Add Sync Status to Main Table
ALTER TABLE enrichment_results
ADD COLUMN IF NOT EXISTS sync_status TEXT DEFAULT 'PENDING';

COMMENT ON COLUMN enrichment_results.sync_status IS 'PENDING, SYNCED, or ERROR';

-- 2. Create History Table (Backup)
-- We clone the structure of enrichment_results but remove unique constraints on account_id
-- to allow multiple historical records for the same account.
CREATE TABLE IF NOT EXISTS enrichment_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Fields from enrichment_results
    status TEXT,
    message TEXT,
    google_place_id TEXT,
    title TEXT,
    address TEXT,
    google_type__c TEXT,
    google_rating__c NUMERIC,
    google_reviews__c INTEGER,
    google_price__c TEXT,
    prospection_status__c TEXT,
    has_google_accept_bookings_extension__c BOOLEAN,
    has_google_delivery_extension__c BOOLEAN,
    has_google_takeout_extension__c BOOLEAN,
    google_url__c TEXT,
    
    -- Metadata
    original_timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for faster lookups
CREATE INDEX IF NOT EXISTS idx_history_account_id ON enrichment_history(account_id);
